# Generated by Django 4.1.3 on 2022-11-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_short_description_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_link',
            field=models.TextField(default=''),
        ),
    ]
