# Generated by Django 4.1.3 on 2022-11-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_github_link_project_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
