# Generated by Django 4.1.3 on 2022-11-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_github_link_alter_project_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('photo', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('experience', models.TextField(default='')),
                ('skills', models.TextField(default='')),
                ('linkedin_link', models.CharField(default='', max_length=200)),
                ('github_link', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
